/* Caroline Tipton, Vanessa Mendoza, Erin Medon */

CREATE TABLE COBRA_INTENTS_EXPLAIN_CODE (
  EXPLAIN_CODE_INT_ID     INT(4) PRIMARY KEY,
  EXPLAIN_CODE_INT_NAME    VARCHAR(20),
  EXPLAIN_CODE_INT_EXAMPLE   VARCHAR(255) NOT NULL,
  BOT_ID  INT,
  FOREIGN KEY (BOT_ID) REFERENCES BOT(BOT_ID)
);

start transaction;
/*DATA STRUCTURES INTENT*/
INSERT INTO COBRA_INTENTS_EXPLAIN_CODE VALUES (701,'Explain_Code', 'How to format various types correctly?',8675309);
commit;

CREATE TABLE COBRA_INTENTS_DATA_STRUCTURES (
  DATA_STRUCTURES_INT_ID     INT(4) PRIMARY KEY,
  DATA_STRUCTURES_INT_NAME    VARCHAR(20),
  DATA_STRUCTURES_INT_EXAMPLE   VARCHAR(255) NOT NULL,
  BOT_ID  INT,
  FOREIGN KEY (BOT_ID) REFERENCES BOT(BOT_ID)
);

start transaction;
/*DATA STRUCTURES INTENT*/
INSERT INTO COBRA_INTENTS_DATA_STRUCTURES VALUES (801,'Data_Structures', 'How to form a tuple?',8675309);
commit;