/* Database Systems */
/* Erin Medon, Caroline Tipton, Vanessa Mendoza */
/* Type of SQL : MySQL  */


CREATE TABLE COBRA_INTENTS_PYTHON_FUNCTIONALITY(
  FUNCTIONALITY_INT_ID            INT(4) NOT NULL PRIMARY KEY,
  FUNCTIONALITY_INT_NAME          VARCHAR(255) NOT NULL,
  FUNCTIONALITY_INT_EXAMPLE       VARCHAR(255) NOT NULL,
  BOT_ID  INT,
  FOREIGN KEY (BOT_ID) REFERENCES BOT(BOT_ID)
);

/*Insert data
  COBRA_INTENT_PYTHON_FUNCTIONALITY */
COMMIT;
INSERT INTO COBRA_INTENTS_PYTHON_FUNCTIONALITY VALUES (1200, 'Python Functionality', 'How is memory managed in Python?',8675309);
INSERT INTO COBRA_INTENTS_PYTHON_FUNCTIONALITY VALUES (1201, 'Python Functionality', 'What are the benefits of using Python?',8675309);
START TRANSACTION;